package com.example.entryrecorder.model

object ApplicationServices {
    val list: List<String> = listOf(
        "Al raji account Opening",
        "Apo-Attached",
        "Apostille",
        "Arivel Card for Visit visa",
        "BD Birth Certificate",
        "BMET Card",
        "BRAC Bank Account Opening (BD)",
        "By Office",
        "CR",
        "Chamber",
        "Commercial Account Open (For Investors)",
        "E-PASS-APPLY",
        "EFA",
        "EX-Jub",
        "EX/DMM Only",
        "EXIT Application",
        "Ex (After MOK)",
        "Ex-O.R",
        "Ex-R",
        "Ex/Dom.",
        "Fine-Pay",
        "Finger For Umrah",
        "Gosi solution",
        "H/X",
        "Hotel Booking (Visit visa holder only)",
        "IBBL A/C",
        "IBBL Celfin",
        "ID-Check",
        "IQ-Insurance",
        "IQ-Medical",
        "IQM N Change",
        "International D.L (For 01 Year)",
        "International D.L (For 02 Years)",
        "International D.L (For 03 Years)",
        "Investor-Service",
        "Investor-Trading",
        "JV (DOM)",
        "JV (Mowassasha)",
        "JV (Sharriqa)",
        "JV Processing",
        "JV-Aply",
        "JV-Ex",
        "JV-Renew (1st & 2nd)",
        "Lost I.C",
        "M/Rx",
        "MLT",
        "MLT Correction",
        "MLT-Hand",
        "MLT-JV",
        "MLT-Lost",
        "MLT-Single",
        "MOFA",
        "Mamla Against kopil /Sponsor",
        "Mamla general",
        "Marriage Certificate (Kabin-BD)",
        "Mehana Change",
        "Misa Renew",
        "Misa update",
        "Moassasah Close",
        "Moassasah Open",
        "Moassasah Transfer",
        "Mudad Update/Wage Protection",
        "NIC",
        "NIN",
        "Nafath Motlob",
        "Nasat update (Without Gov Fee)",
        "Omra Exit",
        "PIN",
        "PIN-PP EXP",
        "Police Clearance - Absher",
        "Police Clearance- 10 Finger",
        "Print -MPT",
        "Print- APT",
        "Print- BPT",
        "Print- DPT",
        "Print- DPT+APT (Together)",
        "Print- JPT",
        "Print- MMP",
        "Print-H.Date",
        "Qiwa (Company)",
        "Quata Balance (Issue)",
        "R/EX",
        "SADDAT Fee",
        "SBC Mowafaka",
        "Salama Licence",
        "Saudi Employee add",
        "Sponsor Contact",
        "Sponsor Transfer",
        "Sponsor Transfer Request Solving (STRS)",
        "TP",
        "Tourist Visa Processing -KUWAIT (Refundable)",
        "Tourist Visa Processing -MALAYSIA (Non-Refundable)",
        "Tourist Visa Processing -OMAN (Non-Refundable)",
        "Tourist Visa Processing -QATAR (Refundable)",
        "Tourist Visa Processing -THAILAND (Non-Refundable)",
        "Travel Pass (Visit visa holder only)",
        "Umrah 14Days",
        "Umrah Family Package",
        "VISA Tolob",
        "VISA Umrah Only",
        "VISA owakala (Amel Idi)",
        "VISA owakala (Domestic)",
        "Vacation/Chuti (Out of Saddat)",
        "Vat Return fo Investors",
        "Wafedin Jubail"
    )
}
